const DEFAULT_ML_SERVICE_URL = 'http://127.0.0.1:8000';
const ML_TIMEOUT_MS = 500;

export function getMlServiceUrl() {
  return process.env.ML_SERVICE_URL || DEFAULT_ML_SERVICE_URL;
}

// Cache of latest prediction per worker
export const latestMlPredictions = new Map();

/**
 * Dispatches live sensor reading to Python ML microservice.
 * Non-blocking, fault-tolerant: never throws or fails ingestion.
 * Enforces strict mq2_mv binding and deterministic alert primacy.
 * Broadcasts 'ml_gas_prediction' or 'ml_gas_readiness' over Socket.IO.
 *
 * @param {Object} reading Ingested sensor reading
 * @param {Array} alertsGenerated Array of alert objects generated by AlertEngine
 * @param {Object} io Socket.IO server instance
 * @returns {Promise<Object|null>} Prediction payload or null if unavailable/failed
 */
export async function evaluateMlGasTrend(reading, alertsGenerated = [], io = null) {
  if (!reading || reading.mq2_mv == null) {
    return null;
  }

  // Strictly bind to mq2_mv; do NOT send or fallback to mq5_mv
  const payload = {
    worker_id: reading.worker_id,
    helmet_id: reading.helmet_id,
    timestamp: reading.timestamp || new Date().toISOString(),
    mq2_mv: reading.mq2_mv,
    temperature: reading.temperature,
    humidity: reading.humidity,
    pressure: reading.pressure
  };

  const serviceUrl = getMlServiceUrl();

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), ML_TIMEOUT_MS);

    const res = await fetch(`${serviceUrl}/predict/gas-trend`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      signal: controller.signal
    });

    clearTimeout(timeoutId);

    if (!res.ok) {
      console.warn(`[ML Service] Prediction request returned status ${res.status}`);
      return null;
    }

    const data = await res.json();

    if (!data.ready) {
      // Warm-up / insufficient history
      if (io) {
        io.emit('ml_gas_readiness', {
          ready: false,
          reason: data.reason || 'INSUFFICIENT_HISTORY',
          current_samples: data.current_samples,
          required_samples: data.required_samples,
          worker_id: reading.worker_id,
          timestamp: data.timestamp
        });
      }
      return data;
    }

    // Deterministic Primacy: If deterministic gas alert is critical, escalate risk_level to CRITICAL_SURGE_RISK
    const hasCriticalGasAlert = (Array.isArray(alertsGenerated) && alertsGenerated.some(
      a => a.type === 'GAS' && a.severity === 'CRITICAL'
    )) || (reading.mq2_mv != null && reading.mq2_mv >= 2500);

    const hasElevatedGasAlert = (reading.mq2_mv != null && reading.mq2_mv >= 2000);

    let effectiveRiskLevel = data.risk_level;
    let effectiveRiskProbability = data.risk_probability;

    if (hasCriticalGasAlert) {
      effectiveRiskLevel = 'CRITICAL_SURGE_RISK';
      effectiveRiskProbability = Math.max(effectiveRiskProbability || 0, 0.92);
    } else if (hasElevatedGasAlert && (!effectiveRiskLevel || effectiveRiskLevel === 'NORMAL')) {
      effectiveRiskLevel = 'ELEVATED_SURGE_RISK';
      effectiveRiskProbability = Math.max(effectiveRiskProbability || 0, 0.68);
    }

    const predictionPayload = {
      timestamp: data.timestamp || reading.timestamp,
      worker_id: reading.worker_id,
      risk_probability: effectiveRiskProbability,
      risk_level: effectiveRiskLevel,
      trend_direction: data.trend_direction || ((hasCriticalGasAlert || hasElevatedGasAlert) ? 'rising' : 'stable'),
      model_version: data.model_version
    };

    latestMlPredictions.set(reading.worker_id, predictionPayload);

    if (io) {
      io.emit('ml_gas_prediction', predictionPayload);
    }

    return predictionPayload;
  } catch (err) {
    if (err.name === 'AbortError') {
      console.warn(`[ML Service] Inference request timed out after ${ML_TIMEOUT_MS}ms`);
    } else {
      console.warn(`[ML Service] Microservice unavailable or error: ${err.message}`);
    }
    return null;
  }
}
